name             'vpnc'
maintainer       'Troy Ready'
maintainer_email 'troy@troyready.com'
license          'apache2'
description      'Installs/Configures vpnc'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.0'
source_url       'https://github.com/troyready/chef-vpnc'
issues_url       'https://github.com/troyready/chef-vpnc/issues'

supports         'amazon'
supports         'centos'
supports         'fedora'
supports         'redhat'
supports         'scientific'
supports         'ubuntu'
